// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zUHqsKVuf_ByTZ0qXYB9-458k6CgZkg',
    appId: '1:341120839996:android:e2f737c6409f67f000ee39',
    messagingSenderId: '341120839996',
    projectId: 'carbonsense-c6f91',
    storageBucket: 'carbonsense-c6f91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5o1Z4SmJiYDRoRujFeZ7xck5Lor2x_U',
    appId: '1:341120839996:ios:02593a89abcd072700ee39',
    messagingSenderId: '341120839996',
    projectId: 'carbonsense-c6f91',
    storageBucket: 'carbonsense-c6f91.firebasestorage.app',
    iosBundleId: 'com.example.carbonsense',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkb1UP_vMAV5DHQK4PecBNxFJ8kexMvZQ',
    appId: '1:341120839996:web:0ce78b234f789b1300ee39',
    messagingSenderId: '341120839996',
    projectId: 'carbonsense-c6f91',
    authDomain: 'carbonsense-c6f91.firebaseapp.com',
    storageBucket: 'carbonsense-c6f91.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS5o1Z4SmJiYDRoRujFeZ7xck5Lor2x_U',
    appId: '1:341120839996:ios:02593a89abcd072700ee39',
    messagingSenderId: '341120839996',
    projectId: 'carbonsense-c6f91',
    storageBucket: 'carbonsense-c6f91.firebasestorage.app',
    iosBundleId: 'com.example.carbonsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkb1UP_vMAV5DHQK4PecBNxFJ8kexMvZQ',
    appId: '1:341120839996:web:3c931ce9e7942c5c00ee39',
    messagingSenderId: '341120839996',
    projectId: 'carbonsense-c6f91',
    authDomain: 'carbonsense-c6f91.firebaseapp.com',
    storageBucket: 'carbonsense-c6f91.firebasestorage.app',
  );

}