import 'dart:async';
import 'package:flutter/material.dart';
import 'package:carbonsense/theme/app_theme.dart';

// 🌟 GLOBAL REUSABLE QUICK START GUIDE DIALOG
void showQuickStartGuideDialog(
  BuildContext context, {
  bool isOnboarding = false, // If true, forces them to stay for 10s. If false, they can exit anytime.
  VoidCallback? onComplete,  // Code to run when they successfully hit the accept button
}) {
  int secondsLeft = 10;
  Timer? localTimer;

  showDialog(
    context: context,
    barrierDismissible: !isOnboarding, // Can't dismiss by tapping background if onboarding
    builder: (BuildContext dialogContext) {
      return StatefulBuilder(
        builder: (context, setDialogState) {
          // Initialize countdown loop
          if (localTimer == null) {
            localTimer = Timer.periodic(const Duration(seconds: 1), (timer) {
              if (secondsLeft > 0) {
                setDialogState(() => secondsLeft--);
              } else {
                timer.cancel();
              }
            });
          }

          return Dialog(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28)),
            backgroundColor: Colors.white,
            child: Container(
              padding: const EdgeInsets.all(24),
              constraints: const BoxConstraints(maxWidth: 500),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(8),
                            decoration: BoxDecoration(color: AppTheme.primaryColor.withOpacity(0.1), shape: BoxShape.circle),
                            child: const Icon(Icons.auto_awesome, color: AppTheme.primaryColor, size: 20),
                          ),
                          const SizedBox(width: 12),
                          const Text(
                            "Quick Start Guide",
                            style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900, letterSpacing: -0.5),
                          ),
                        ],
                      ),
                      // Always show close button if accessed as a reference tool outside onboarding
                      if (!isOnboarding) 
                        IconButton(
                          icon: const Icon(Icons.close, size: 20, color: Colors.grey),
                          onPressed: () {
                            localTimer?.cancel();
                            Navigator.pop(dialogContext);
                          },
                        ),
                    ],
                  ),
                  const Divider(height: 32),
                  
                  Flexible(
                    child: SingleChildScrollView(
                      physics: const BouncingScrollPhysics(),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text("What is a Carbon Footprint?", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Colors.black87)),
                          const SizedBox(height: 6),
                          Text(
                            "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our collective daily actions. From the electricity powering your home to the transport methods you choose, every choice leaves an environmental trace.",
                            style: TextStyle(fontSize: 13, color: Colors.grey.shade700, height: 1.5),
                          ),
                          const SizedBox(height: 16),
                          
                          const Text("The Vital Impact of Mitigation", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Colors.black87)),
                          const SizedBox(height: 6),
                          Text(
                            "Mitigating and lowering carbon emissions is critical to slowing climate instability, preserving baseline ecosystem biodiversity, and securing cleaner public breathing spaces. Small, intentional changes across millions of individuals compound into major planetary transformations.",
                            style: TextStyle(fontSize: 13, color: Colors.grey.shade700, height: 1.5),
                          ),
                          const SizedBox(height: 16),
                          
                          const Text("What is CarbonSense?", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Colors.black87)),
                          const SizedBox(height: 6),
                          Text(
                            "CarbonSense is your personal environmental accounting assistant and ecosystem coach. We help you map out your footprint metrics through seamless tracking utilities, translate telemetry logs into localized dynamic insights, and supply actionable weekly missions to refine your lifestyle footprint sustainably.",
                            style: TextStyle(fontSize: 13, color: Colors.grey.shade700, height: 1.5),
                          ),
                        ],
                      ),
                    ),
                  ),
                  
                  const Divider(height: 32),
                  
                  SizedBox(
                    width: double.infinity,
                    height: 48,
                    child: ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        backgroundColor: secondsLeft > 0 ? Colors.grey.shade300 : AppTheme.primaryColor,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                        elevation: 0,
                      ),
                      onPressed: secondsLeft > 0 
                          ? null 
                          : () {
                              localTimer?.cancel();
                              Navigator.pop(dialogContext);
                              if (onComplete != null) onComplete();
                            },
                      child: Text(
                        secondsLeft > 0 
                            ? "Please read carefully ($secondsLeft)..." 
                            : "I Understand, Let's Go!", 
                        style: TextStyle(
                          color: secondsLeft > 0 ? Colors.black38 : Colors.white, 
                          fontWeight: FontWeight.bold, 
                          fontSize: 14,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      );
    },
  );
}